-- | Generic class of errors generated by the minijuvix compiler. Inspired by
-- Control.Exception
module MiniJuvix.Prelude.Error
  ( module MiniJuvix.Prelude.Error,
    module MiniJuvix.Syntax.Concrete.Loc,
  )
where

import MiniJuvix.Prelude.Base
import MiniJuvix.Prelude.Pretty
import MiniJuvix.Syntax.Concrete.Loc
import Prettyprinter.Render.Terminal qualified as Ansi
import Prettyprinter.Render.Text
import System.Console.ANSI qualified as Ansi

data GenericError = GenericError
  { _genericErrorLoc :: Loc,
    _genericErrorFile :: FilePath,
    _genericErrorMessage :: AnsiText,
    _genericErrorIntervals :: [Interval]
  }

makeLenses ''GenericError

instance Pretty GenericError where
  pretty :: GenericError -> Doc a
  pretty g =
    let lineNum = g ^. genericErrorLoc . locFileLoc . locLine
        colNum = g ^. genericErrorLoc . locFileLoc . locCol
     in pretty (g ^. genericErrorFile)
          <> colon
          <> pretty lineNum
          <> colon
          <> pretty colNum
          <> colon <+> "error"
          <> colon
          <> line
          <> pretty (g ^. genericErrorMessage)

class ToGenericError a where
  genericError :: a -> Maybe GenericError

instance ToGenericError Text where
  genericError = const Nothing

-- TODO: throw a generic error showing which object
-- doesn't have implemented ToGenericError
toGenericError :: ToGenericError e => e -> GenericError
toGenericError x = fromMaybe (error "Report this!") (genericError x)

data MiniJuvixError
  = forall a. (ToGenericError a, Typeable a) => MiniJuvixError a

instance ToGenericError MiniJuvixError where
  genericError (MiniJuvixError e) = genericError e

fromMiniJuvixError :: Typeable a => MiniJuvixError -> Maybe a
fromMiniJuvixError (MiniJuvixError e) = cast e

errorIntervals :: ToGenericError e => e -> [Interval]
errorIntervals = maybe [] (^. genericErrorIntervals) . genericError

-- runErrorIO'
-- ((embed . hPutStrLn stderr . render) e) >> exitFailure

render :: ToGenericError e => Bool -> e -> Text
render ansi err = render' ansi (toGenericError err)

render' :: Bool -> GenericError -> Text
render' ansi g
  | ansi =
      Ansi.renderStrict
        ( layoutPretty
            defaultLayoutOptions
            (header <> toAnsiDoc (g ^. genericErrorMessage) <> endChar)
        )
  | otherwise =
      renderStrict
        ( layoutPretty
            defaultLayoutOptions
            (header <> toTextDoc (g ^. genericErrorMessage) <> endChar)
        )
  where
    header :: Doc a
    header =
      let lineNum = g ^. genericErrorLoc . locFileLoc . locLine
          colNum = g ^. genericErrorLoc . locFileLoc . locCol
       in pretty (g ^. genericErrorFile)
            <> colon
            <> pretty lineNum
            <> colon
            <> pretty colNum
            <> colon <+> "error"
            <> colon
            <> line
    endChar :: Doc a
    endChar = "ת"

-- | Render the error to Text.
renderText :: ToGenericError e => e -> Text
renderText = render False

-- | Render the error with Ansi formatting (if any).
renderAnsiText :: ToGenericError e => e -> Text
renderAnsiText = render True

printErrorAnsi :: ToGenericError e => e -> IO ()
printErrorAnsi = hPutStrLn stderr . renderAnsiText

-- | Print the error to stderr without formatting.
printErrorText :: ToGenericError e => e -> IO ()
printErrorText = hPutStrLn stderr . renderText

printErrorAnsiSafe :: ToGenericError e => e -> IO ()
printErrorAnsiSafe e =
  ifM
    (Ansi.hSupportsANSI stderr)
    (printErrorAnsi e)
    (printErrorText e)

runErrorIO ::
  (ToGenericError a, Member (Embed IO) r) =>
  Sem (Error a ': r) b ->
  Sem r b
runErrorIO =
  runError >=> \case
    Left err -> embed (printErrorAnsiSafe err >> exitFailure)
    Right a -> return a
